### ISSUE TITLE
[OTHER] Rivalutare i pacchetti inviati dal gateway

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-gateway#22]
## Cambiamenti per i pacchetti inviati a Kafka

I pacchetti inviati dal gateway dovranno contenere solamente un array di sensori registrati, con il relativo id dispositivo e valore. 

- Il timestamp verrà generato direttamente nel DB --> Maggiore inconsistenza in caso di intasamento dei dati, minore peso del pacchetto, nessun rischio di primary key
- Il timestamp viene generato all'invio del pacchetto --> Maggiore peso del pacchetto, una operazione in meno per il DB, rischio di coincidenza con la primary key

> Quale conviene fare?

**Comment by lorenzodeinegri** [comment]
Secondo me la scelta più giusta è la seconda, perché il timestamp deve essere più vicino possibile al vero orario di rilevazione del dato, quindi spostarlo nel db causerebbe un delta maggiore.
Inoltre l'aumento di peso del pacchetto non penso sia così incidente alla fine dei conti.
Non capisco però cosa intendi con "rischio di coincidenza con la primary key"

**Comment by nfrison** [comment]
Il timestamp viene generato a db come chiave primaria, e in un campo req_time viene salvato il timestamp di quando è stato richiesto il dato al dispositivo
